### ISSUE TITLE
Perpectives support

### ISSUE THREAD

**Issue by luizhop** [sanity-io/sanity-php#34]
Hello there 👋 

First of all, really appreciate your work with this library! We are just starting to use Sanity on the company I work for, and having a PHP library to start with is definitely helping a lot, as most our projects are PHP based.

I see Perspectives is something relatively new to Sanity and found a working branch on this repository with changes to implement it, so currently I am using this working branch on my project and wondering are there still active plans to merge it into main?

While using it on my project I saw a notice on error.log, undefined index clientConfig on line 70 of sanity-php/lib/Client.php:
https://github.com/sanity-io/sanity-php/blob/7520615550075eab491152dbb3c7fc6e81d75632/lib/Client.php#L70C79-L70C91

So I've created a pull request with what I believe would be the fix for that: https://github.com/sanity-io/sanity-php/pull/33

Many thanks!

**Comment by sjelfull** [comment]
Hey, thanks for the PR and the reminder. I have tagged [v1.5.2](https://github.com/sanity-io/sanity-php/releases/tag/v1.5.2) that includes perspectives support.

**Comment by luizhop** [comment]
Many thanks for that @sjelfull 😄
